// Auto-generated by scripts/generate-pokoracle-vo.mjs — do not edit manually.
// Voice ID used: pNInz6obpgDQGcFmaJgB
export const FPS = 30;
export const SCENE_DURATIONS_S: (number | null)[] = [null, 16.22, 15.07, 54.73, 82.96, 56.11, 33.78];
export const SCENE_DURATION_FRAMES: number[] = [90, 522, 488, 1677, 2524, 1719, 1049];
export const SCENE_START_FRAMES: number[] = [0, 78, 588, 1064, 2729, 5241, 6948];
export const TOTAL_FRAMES = 7997;
