// Auto-generated by scripts/generate-voiceover.mjs — do not edit manually.
export const FPS = 30;
export const STEP_START_FRAMES: number[] = [0, 618, 1158, 1656, 2100];
export const STEP_DURATIONS_S: number[]  = [20.6, 18, 16.6, 14.8, 16.3];
export const FINAL_SCENE_FRAME = 2589;
export const TOTAL_FRAMES = 2769;
